# Generated by Django 4.2.1 on 2023-05-26 15:22

from django.db import migrations, models
import vacancies.models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_vacancy_min_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='update_at',
            field=models.DateField(null=True, validators=[vacancies.models.check_date_not_past]),
        ),
    ]
